"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";

type Notification = { id:string; type:string; title:string; body:string|null; link_url:string|null; read_at:string|null; created_at:string };
const labels: Record<string,string> = { offer:"Nova oferta", invitation:"Convite", offer_accepted:"Oferta aceita", offer_declined:"Oferta recusada", counterproposal:"Contraproposta", booking:"Contratação", message:"Mensagem", event_changed:"Alteração do evento", payment:"Pagamento", in_transit:"Deslocamento iniciado", arrived:"Artista chegou", completed:"Evento finalizado", review_request:"Avalie o evento" };
export default function NotificationsPage() {
  const router=useRouter(); const [items,setItems]=useState<Notification[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{ void (async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/login");return;} const {data,error}=await supabase.from("notifications").select("id,type,title,body,link_url,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100); if(error)setError(error.message); else setItems((data||[]) as Notification[]); setLoading(false); })(); },[router]);
  async function mark(id?:string){ const {data:{user}}=await supabase.auth.getUser(); if(!user)return; let query=supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("user_id",user.id).is("read_at",null); if(id) query=query.eq("id",id); await query; setItems(old=>old.map(n=>!id||n.id===id?{...n,read_at:new Date().toISOString()}:n)); }
  return <main className="mx-auto min-h-screen max-w-4xl px-4 py-8"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-red-400">CENTRAL</p><h1 className="text-3xl font-black">Notificações</h1></div><button onClick={()=>mark()} className="rounded-xl border border-zinc-700 px-4 py-2 text-sm">Marcar todas como lidas</button></div>
  {loading?<p className="mt-10 text-zinc-400">Carregando notificações…</p>:error?<div role="alert" className="mt-8 rounded-2xl border border-red-900 bg-red-950/20 p-4 text-red-300">Não foi possível carregar: {error}</div>:items.length===0?<div className="mt-8 rounded-3xl border border-dashed border-zinc-800 p-12 text-center"><div className="text-4xl">♢</div><h2 className="mt-3 font-bold">Tudo em dia</h2><p className="text-sm text-zinc-500">Novidades de ofertas, eventos e mensagens aparecerão aqui.</p></div>:<div className="mt-6 space-y-3">{items.map(n=><Link href={n.link_url||"/notificacoes"} onClick={()=>mark(n.id)} key={n.id} className={`block rounded-2xl border p-4 ${n.read_at?"border-zinc-900 bg-zinc-950":"border-red-500/30 bg-red-500/5"}`}><div className="flex justify-between gap-4"><div><p className="text-xs font-bold text-red-400">{labels[n.type]||n.type}</p><h2 className="font-bold">{n.title}</h2>{n.body&&<p className="mt-1 text-sm text-zinc-400">{n.body}</p>}</div><time className="shrink-0 text-xs text-zinc-600">{new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(n.created_at))}</time></div></Link>)}</div>}</main>;
}
