"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";
import { formatBRL } from "../../lib/finance";
type Artist={id:string;stage_name:string;city:string|null;state:string|null;style:string|null;fixed_fee:number|null;is_verified:boolean|null;avatar_url:string|null};
export default function SearchPage(){const router=useRouter();const [artists,setArtists]=useState<Artist[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const {data,error}=await supabase.from("artist_profiles").select("id,stage_name,city,state,style,fixed_fee,is_verified,avatar_url").eq("is_active",true).order("stage_name").limit(100);if(error)setError(error.message);else setArtists((data||[]) as Artist[]);setLoading(false)})()},[router]);
const filtered=useMemo(()=>artists.filter(a=>`${a.stage_name} ${a.style||""} ${a.city||""}`.toLowerCase().includes(query.toLowerCase())),[artists,query]);
return <main className="mx-auto min-h-screen max-w-6xl px-4 py-8"><p className="text-sm font-bold text-purple-400">DESCUBRA TALENTOS</p><h1 className="text-3xl font-black">Buscar artistas</h1><p className="mt-2 text-zinc-400">Compare estilo, localização e cachê por hora.</p><label className="mt-6 block"><span className="sr-only">Buscar por nome, estilo ou cidade</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, estilo ou cidade…" className="w-full rounded-2xl border border-zinc-800 bg-zinc-950 px-5 py-4"/></label>
{loading?<p className="mt-8 text-zinc-500">Buscando artistas…</p>:error?<p role="alert" className="mt-8 text-red-400">{error}</p>:<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(a=><article key={a.id} className="rounded-3xl border border-zinc-800 bg-zinc-950 p-5"><div className="flex items-start gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-red-500 to-purple-700 text-xl font-black">{a.stage_name.charAt(0)}</div><div><h2 className="font-bold">{a.stage_name} {a.is_verified&&<span title="Artista verificado" className="text-blue-400">✓</span>}</h2><p className="text-sm text-zinc-400">{a.style||"Estilos diversos"}</p><p className="text-xs text-zinc-500">{[a.city,a.state].filter(Boolean).join(" — ")||"Localização não informada"}</p></div></div><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-zinc-500">Cachê por hora</p><p className="font-black text-red-400">{formatBRL(Number(a.fixed_fee||0))}/h</p></div><Link href={`/ofertas?artist=${a.id}`} className="rounded-xl bg-red-500 px-4 py-2 text-sm font-bold">Enviar oferta</Link></div></article>)}{filtered.length===0&&<p className="text-zinc-500">Nenhum artista encontrado.</p>}</div>}</main>}
