-- 2026-09-21
-- Central de Planos: metadados administrativos e histórico automático.

alter table public.subscriptions
  add column if not exists assignment_source text not null default 'system',
  add column if not exists admin_note text,
  add column if not exists assigned_by_user_id uuid,
  add column if not exists cancelled_by_user_id uuid,
  add column if not exists cancelled_at timestamptz;

update public.subscriptions
set assignment_source = case
  when provider = 'manual_admin' then 'manual_admin'
  when provider = 'asaas' then 'asaas'
  else coalesce(nullif(provider,''),'system')
end
where assignment_source = 'system';

create table if not exists public.subscription_history (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null,
  event_type text not null,
  plan_id uuid not null,
  artist_id uuid,
  venue_id uuid,
  status text not null,
  assignment_source text not null default 'system',
  provider text,
  period_start timestamptz,
  period_end timestamptz,
  unlimited boolean not null default false,
  actor_user_id uuid,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint subscription_history_one_target_ck
    check ((artist_id is not null) <> (venue_id is not null))
);

alter table public.subscription_history enable row level security;

revoke all on public.subscription_history from public,anon,authenticated;
revoke all on sequence public.subscription_history_id_seq from public,anon,authenticated;

create index if not exists subscription_history_subscription_idx
  on public.subscription_history(subscription_id,created_at desc);

create index if not exists subscription_history_artist_idx
  on public.subscription_history(artist_id,created_at desc)
  where artist_id is not null;

create index if not exists subscription_history_venue_idx
  on public.subscription_history(venue_id,created_at desc)
  where venue_id is not null;

create or replace function public.capture_subscription_history_v1()
returns trigger
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_event text;
  v_actor uuid := auth.uid();
  v_source text;
begin
  if tg_op = 'INSERT' then
    v_event := 'created';
  elsif tg_op = 'UPDATE' then
    if old.status is distinct from new.status and new.status='cancelled' then
      v_event := 'cancelled';
    elsif old.plan_id is distinct from new.plan_id then
      v_event := 'plan_changed';
    elsif old.current_period_end is distinct from new.current_period_end then
      v_event := 'period_changed';
    elsif old.status is distinct from new.status then
      v_event := 'status_changed';
    else
      v_event := 'updated';
    end if;
  else
    return new;
  end if;

  v_source := case
    when new.provider='asaas'
      and coalesce(nullif(new.assignment_source,''),'system')='system'
      then 'asaas'
    else coalesce(
      nullif(new.assignment_source,''),
      nullif(new.provider,''),
      'system'
    )
  end;

  insert into public.subscription_history(
    subscription_id,event_type,plan_id,artist_id,venue_id,status,
    assignment_source,provider,period_start,period_end,unlimited,
    actor_user_id,note,metadata
  )
  values(
    new.id,v_event,new.plan_id,new.artist_id,new.venue_id,new.status,
    v_source,new.provider,new.current_period_start,new.current_period_end,
    new.current_period_end is null,
    coalesce(new.cancelled_by_user_id,new.assigned_by_user_id,v_actor),
    new.admin_note,
    jsonb_build_object(
      'trial_ends_at',new.trial_ends_at,
      'cancelled_at',new.cancelled_at
    )
  );

  return new;
end;
$function$;

revoke all on function public.capture_subscription_history_v1()
from public,anon,authenticated;

drop trigger if exists trg_capture_subscription_history_v1
on public.subscriptions;

create trigger trg_capture_subscription_history_v1
after insert or update on public.subscriptions
for each row
execute function public.capture_subscription_history_v1();

insert into public.subscription_history(
  subscription_id,event_type,plan_id,artist_id,venue_id,status,
  assignment_source,provider,period_start,period_end,unlimited,
  actor_user_id,note,metadata,created_at
)
select
  s.id,
  'created',
  s.plan_id,
  s.artist_id,
  s.venue_id,
  s.status,
  coalesce(nullif(s.assignment_source,''),nullif(s.provider,''),'system'),
  s.provider,
  s.current_period_start,
  s.current_period_end,
  s.current_period_end is null,
  s.assigned_by_user_id,
  s.admin_note,
  jsonb_build_object('backfilled',true,'trial_ends_at',s.trial_ends_at),
  s.created_at
from public.subscriptions s
where not exists (
  select 1
  from public.subscription_history h
  where h.subscription_id=s.id
);

create or replace function public.owner_assign_subscription_v3(
  p_plan_id uuid,
  p_artist_id uuid default null,
  p_venue_id uuid default null,
  p_status text default 'active',
  p_period_months integer default 1,
  p_unlimited boolean default false,
  p_source text default 'manual_admin',
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_plan public.plans%rowtype;
  v_subscription_id uuid;
  v_now timestamptz := now();
  v_period_end timestamptz;
  v_unlimited boolean := coalesce(p_unlimited,false) or coalesce(p_period_months,0)=0;
  v_note text := nullif(trim(coalesce(p_note,'')),'');
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.aura_admins aa
    where aa.user_id=auth.uid()
      and aa.is_active=true
      and aa.role='owner'
  ) then
    raise exception 'owner access required';
  end if;

  if (p_artist_id is null)=(p_venue_id is null) then
    raise exception 'Informe exatamente um Artista ou uma Casa';
  end if;

  if p_status not in ('trialing','active') then
    raise exception 'Status inválido para nova assinatura';
  end if;

  if p_source not in (
    'manual_admin','courtesy','partnership','trial','adjustment'
  ) then
    raise exception 'Origem inválida';
  end if;

  if not v_unlimited then
    if p_period_months is null or p_period_months<1 or p_period_months>120 then
      raise exception 'Período deve ficar entre 1 e 120 meses';
    end if;
    v_period_end := v_now + make_interval(months=>p_period_months);
  else
    v_period_end := null;
  end if;

  select *
  into v_plan
  from public.plans
  where id=p_plan_id;

  if not found then
    raise exception 'Plano não encontrado';
  end if;

  if not v_plan.is_active then
    raise exception 'Este plano está desativado';
  end if;

  if p_artist_id is not null and v_plan.audience<>'artist' then
    raise exception 'Este plano não pertence a Artistas';
  end if;

  if p_venue_id is not null and v_plan.audience<>'venue' then
    raise exception 'Este plano não pertence a Casas';
  end if;

  if p_artist_id is not null and not exists (
    select 1 from public.artist_profiles a
    where a.id=p_artist_id and coalesce(a.is_active,true)=true
  ) then
    raise exception 'Artista não encontrado ou inativo';
  end if;

  if p_venue_id is not null and not exists (
    select 1 from public.venue_profiles v
    where v.id=p_venue_id and coalesce(v.is_active,true)=true
  ) then
    raise exception 'Casa não encontrada ou inativa';
  end if;

  update public.subscriptions
  set
    status='cancelled',
    current_period_end=coalesce(current_period_end,v_now),
    cancelled_at=v_now,
    cancelled_by_user_id=auth.uid(),
    admin_note=coalesce(
      admin_note,
      'Substituído por uma nova atribuição administrativa'
    ),
    updated_at=v_now
  where status in ('trialing','active','past_due')
    and (
      (p_artist_id is not null and artist_id=p_artist_id)
      or
      (p_venue_id is not null and venue_id=p_venue_id)
    );

  insert into public.subscriptions(
    plan_id,artist_id,venue_id,status,trial_ends_at,
    current_period_start,current_period_end,provider,
    provider_subscription_id,assignment_source,admin_note,
    assigned_by_user_id,cancelled_by_user_id,cancelled_at
  )
  values(
    p_plan_id,p_artist_id,p_venue_id,p_status,
    case
      when p_status='trialing'
      then v_now + make_interval(
        days=>coalesce((v_plan.benefits->>'trial_days')::integer,30)
      )
      else null
    end,
    v_now,v_period_end,'manual_admin',null,p_source,v_note,
    auth.uid(),null,null
  )
  returning id into v_subscription_id;

  insert into public.admin_logs(
    actor_user_id,action,entity_type,entity_id,after_data
  )
  values(
    auth.uid(),
    'subscription_assigned',
    'subscription',
    v_subscription_id::text,
    jsonb_build_object(
      'plan_id',p_plan_id,
      'artist_id',p_artist_id,
      'venue_id',p_venue_id,
      'status',p_status,
      'period_months',case when v_unlimited then 0 else p_period_months end,
      'unlimited',v_unlimited,
      'source',p_source,
      'note',v_note
    )
  );

  return v_subscription_id;
end;
$function$;

revoke all on function public.owner_assign_subscription_v3(
  uuid,uuid,uuid,text,integer,boolean,text,text
) from public,anon;

grant execute on function public.owner_assign_subscription_v3(
  uuid,uuid,uuid,text,integer,boolean,text,text
) to authenticated;

create or replace function public.owner_cancel_subscription_v2(
  p_subscription_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_before jsonb;
  v_reason text := nullif(trim(coalesce(p_reason,'')),'');
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.aura_admins aa
    where aa.user_id=auth.uid()
      and aa.is_active=true
      and aa.role='owner'
  ) then
    raise exception 'owner access required';
  end if;

  select to_jsonb(s)
  into v_before
  from public.subscriptions s
  where s.id=p_subscription_id;

  if v_before is null then
    raise exception 'Assinatura não encontrada';
  end if;

  update public.subscriptions
  set
    status='cancelled',
    current_period_end=coalesce(current_period_end,now()),
    cancelled_at=now(),
    cancelled_by_user_id=auth.uid(),
    admin_note=coalesce(v_reason,admin_note),
    updated_at=now()
  where id=p_subscription_id;

  insert into public.admin_logs(
    actor_user_id,action,entity_type,entity_id,before_data,after_data
  )
  values(
    auth.uid(),
    'subscription_cancelled',
    'subscription',
    p_subscription_id::text,
    v_before,
    jsonb_build_object('reason',v_reason)
  );
end;
$function$;

revoke all on function public.owner_cancel_subscription_v2(uuid,text)
from public,anon;

grant execute on function public.owner_cancel_subscription_v2(uuid,text)
to authenticated;

create or replace function public.owner_plan_history_v1(
  p_limit integer default 250
)
returns table(
  history_id bigint,
  subscription_id uuid,
  event_type text,
  status text,
  plan_id uuid,
  plan_name text,
  monthly_price numeric,
  audience text,
  profile_id uuid,
  profile_name text,
  assignment_source text,
  provider text,
  period_start timestamptz,
  period_end timestamptz,
  unlimited boolean,
  actor_user_id uuid,
  note text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=''
stable
as $function$
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if not exists (
    select 1
    from public.aura_admins aa
    where aa.user_id=auth.uid()
      and aa.is_active=true
      and aa.role='owner'
  ) then
    raise exception 'owner access required';
  end if;

  return query
  select
    h.id,
    h.subscription_id,
    h.event_type,
    h.status,
    h.plan_id,
    p.name,
    p.monthly_price,
    case when h.artist_id is not null
      then 'artist'::text
      else 'venue'::text
    end,
    coalesce(h.artist_id,h.venue_id),
    coalesce(a.stage_name,v.trade_name,'Perfil removido'),
    h.assignment_source,
    h.provider,
    h.period_start,
    h.period_end,
    h.unlimited,
    h.actor_user_id,
    h.note,
    h.created_at
  from public.subscription_history h
  left join public.plans p on p.id=h.plan_id
  left join public.artist_profiles a on a.id=h.artist_id
  left join public.venue_profiles v on v.id=h.venue_id
  order by h.created_at desc
  limit greatest(1,least(coalesce(p_limit,250),500));
end;
$function$;

revoke all on function public.owner_plan_history_v1(integer)
from public,anon;

grant execute on function public.owner_plan_history_v1(integer)
to authenticated;

notify pgrst,'reload schema';
